#!/bin/sh

# Setup environment variables
export ETH=1
export IP1=192.35.192.83  # client IP
export IP2=192.35.192.108  # server IP

OUTPUT=output


echo "Compiling tests" > $OUTPUT
echo `date` >> $OUTPUT
echo >> $OUTPUT

cd tests
make clean > /dev/null 2>> ../$OUTPUT
make all > /dev/null 2>> ../$OUTPUT
cd ..

echo >> $OUTPUT

echo "Starting automated tests" >> $OUTPUT
echo `date` >> $OUTPUT
echo >> $OUTPUT

for i in $( ls build/ | grep -v svn ); do

    echo "* Test $i.c" >> $OUTPUT
    build/$i > /dev/null 2>> $OUTPUT ; sleep .2
    echo >> $OUTPUT

done

echo `date` >> $OUTPUT
echo "Completed automated tests" >> $OUTPUT

cat $OUTPUT
