#!/bin/sh

# Setup environment variables
export ETH=1
export IP1=192.168.0.1  # client IP
export IP2=192.168.0.2  # server IP

OUTPUT=test_output


echo "Starting automated tests" > $OUTPUT
echo `date` >> $OUTPUT
echo >> $OUTPUT

for i in $( ls build/ ); do

    echo "* Test $i.c" >> $OUTPUT
    build/$i > /dev/null 2>> $OUTPUT ; sleep .2
    echo >> $OUTPUT

done

echo `date` >> $OUTPUT
echo "Completed automated tests" >> $OUTPUT

cat $OUTPUT
